# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c88943b82f7179c9a7066920c4dc29e24bf38c3af1c316782f944c51004ba26d90c33fb5e36c24914e9ed99535921d179de43ee6faf792b4bea72c4a67044e4

test:
  secret_key_base: a477da86be3c878720fc8a7f6715328dffbbfac69c8ce4cf2567ebb79240a212555b1fe2839d4de25553fcf5f83ee99a8413e1b5e72e60c9c648c97fa45da1e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
